---
- name: Testing andrewrothstein.dumb_init
  hosts: all
  tasks:
    - name: Installing andrewrothstein.dumb_init
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'dumb-init --version'
      ansible.builtin.command: /usr/local/bin/dumb-init --version
      changed_when: false
      register: dumb_init_test_output
    - name: Output from 'dumb-init --version'
      ansible.builtin.debug:
        msg: '{{ dumb_init_test_output.stderr }}'
