---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/dumb-init --version
      register: dumb_init_test_output
    - name: dumb-init --version
      debug:
        msg: '{{ dumb_init_test_output.stderr }}'
